### ISSUE TITLE
Miscellaneous copy changes

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#112]
Various copy changes throughout the site: 

_Edited on 5/25/2021 based on Colin's comments and additional feedback from CSG_
## Jails
- "Jail Confinement Rate" instead of "Incarceration Rate" 
- "Counties Reporting" to “Counties Represented”
- "Statewide Confinement Rate" (for both the title of the graph and the legend) 

## Corrections
- "Post-Release Supervision" instead of "Parole" 
- "Releases to Community (without supervision)" instead of "Releases to Liberty" 

@colincadams to double-check if there was anything else i missed!

**Comment by colincadams** [comment]
I couldn't really tell whether we reached a decision on any of these in the meeting, so I will use this as an opportunity to push my opinions 😁 

I don't find that "Confinement Rate" really clarifies that this does not include the prison population. I prefer "Jail Incarceration Rate" as it seems most widely used and thus likely to be understood but am also fine with "Jail Confinement Rate". I recognize both of these are quite long haha.

To clarify, do you imagine the "Statewide Confinement Rate" text would be used in both the Key Insights (instead of "Incarceration Rate (per 100,000)" or only in the graph (so title would become "Statewide Confinement Rate vs County Confinement Rates"? or just the label in the legend would become "Statewide Confinement Rate"?).

I think this covers the random label copy changes, only other thing is methodology!

**Comment by nasaownsky** [comment]
@colincadams @hobuobi So, what agreement did you come to?

**Comment by hobuobi** [comment]
Apologies, Colin and I discussed this separately and most of the changes
are now reflected in the original issue!

**Comment by jessex** [comment]
Closed by #117
