### ISSUE TITLE
Key Insights feature functionality

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#27]
Involves the following: 

- Connect the Key Insights blocks (already built) to the data in the fixture files. 
- Implement the "dynamic captions" (text changes according to the data they are supposed to describe). 
- Mobile implementation (described in #14).

**Comment by Wmaileq** [comment]
@hobuobi I found that the first 3 metrics appear in the flow diagram but the last 2 are not, what are the metric names in source files for: "Parole, Technical Revocations" and "Probation, Technical Revocations"?

**Comment by colincadams** [comment]
@Wmaileq sorry for the delay on this! I added all the new metrics [to this doc](https://docs.google.com/document/d/14RZM1KchEnMrc19vpr_kKxWE3bY2BhGzoMEP37Fra30/edit), I think it covers everything you need, let me know if not. Note that in the process I ended up renaming some of the metrics (e.g. ADMISSIONS_REVOCATIONS_PAROLE to ADMISSIONS_FROM_PAROLE) to align better with our data model naming.

We also added a page to the mocks that shows which metric each UI element should use since it isn't always obvious: https://www.figma.com/file/66HyjH0efZMoAuTlhnojWh/Justice-Counts-Report?node-id=686%3A551

The original fixture file does not align with this renaming or include any of the new names. I'll work on getting you an updated fixture file with more real data soon.
