### ISSUE TITLE
[Corrections] Minor Chart Adjustments

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/justice-counts-components#53]
- When only a single data point is available, show a single dot (currently invisible without hovering). 
- Numbers in the tooltips should have commas to separate the thousands (i.e., “1,000,000” instead of “1,000”).
- Tooltip should include the date as "[Month] [Year]" (e.g., February 2020). See image below. 
![Group 61](https://user-images.githubusercontent.com/7134733/107657277-e3758e80-6c39-11eb-8bb7-c7e86ee64023.png)
- Numbers on the y-axis should have commas to separate the thousands (i.e., “1,000,000” instead of “1,000”).
- When the net change is 0, the resulting % in the legend should be “0%” not “+0%”. 
- Upper padding of the chart on mobile is too tight 
- Lines and points should still be drawn for zero values (see below example, Wisconsin:Probation Revocations:New Crime). 
![image](https://user-images.githubusercontent.com/7134733/107657898-74e50080-6c3a-11eb-95e9-715f4861f073.png)
- "Not Available" label should have a white background and be centered vertically and horizontally in the chart canvas.

**Comment by Wmaileq** [comment]
@hobuobi Couldn't reproduce this one 

> Lines and points should still be drawn for zero values (see below example, Wisconsin:Probation Revocations: New Crime).

For me, metrics, where 0 value is situated, renders normally.
Could you, please provide the corresponding fixture?

**Comment by jessex** [comment]
@hobuobi could you also do a quick test on this one, and respond to the comment from Vlad above? He needs fixture data to reproduce one of the issues you called out. I've done a quick review and I think he's solved all of the issues that are testable from my end but I want you to sign off.

**Comment by hobuobi** [comment]
I'll actually pass this one to @colincadams since he's the one who caught it! I've also had some trouble reproducing it 😅

**Comment by colincadams** [comment]
I noticed this on WV revocations data:

![Screen Shot 2021-02-17 at 10 26 17 AM](https://user-images.githubusercontent.com/3762913/108249968-95b1c800-710a-11eb-9f83-172487bf5266.png)

Now that we draw a line across months where data is "missing" it isn't as obvious, but if you hover over the parole revocations line you'll notice that there are months where new crime doesn't show up in the tooltip, when it should be present with a value of 0.

It is a bit more apparent in the probation revocations since the values are zero for the past few months so the line just stops entirely.

It seems like the graph is treating a value of zero as missing when it should instead display it as a normal point.

**Comment by jessex** [comment]
@Wmaileq can you address Colin's comment above and Humphrey's comment on #61 tomorrow? Thanks!
